In [1]:
import cv2
import sys
import numpy as np

In [4]:
src = cv2.imread("./fig/puppy.bmp")
alpha_image = cv2.imread("./fig2/fig/imgbin_sunglasses_1.png",cv2.IMREAD_UNCHANGED)

glass_resize = cv2.resize(alpha_image,(300,150), interpolation = cv2.INTER_AREA)

h,w = glass_resize.shape[:2]

crop = src[120:120+h,220:220+w]

mask = alpha_image[:,:,-1]
glass = alpha_image[:,:,0:3]

cv2.imshow("src",src)
cv2.imshow("alpha",alpha_image)
cv2.imshow("glass",glass_resize)


cv2.waitKey()
cv2.destroyAllWindows()

In [121]:
src = cv2.imread("./fig/puppy.bmp")
hat = cv2.imread("./fig2/fig/hat_alpha.png",cv2.IMREAD_UNCHANGED)
glasses = cv2.imread("./fig2/fig/imgbin_sunglasses_1.png",cv2.IMREAD_UNCHANGED)

hat = cv2.resize(hat,(300,150),interpolation=cv2.INTER_AREA)
glasses = cv2.resize(glasses,(300,150),interpolation=cv2.INTER_AREA)


mask_hat = hat[:,:,0:3]
alpha_hat = mask_hat[:,:,-1]

print(alpha_hat.shape)
print(mask_hat.shape)
print(alpha_glasses.shape)
print(mask_glasses.shape)

mask_hat[ mask_hat>=237] = 0
mask_hat[ mask_hat != 0] = 255

alpha_glasses = glasses[:,:,-1]
mask_glasses = glasses[:,:,0:3]


h, w = hat.shape[:2]

src_hat = src[10:10+h,220:220+w]
src_glasses = src[120:120+h,220:220+w]

cv2.copyTo(mask_hat,alpha_hat,src_hat)
cv2.copyTo(mask_glasses,alpha_glasses,src_glasses)
cv2.imshow("g",alpha_glasses)
cv2.imshow("hat",src)
cv2.imshow("alpha_hat",alpha_hat)
cv2.imshow("mask_hat",mask_hat)

cv2.imwrite("./fig/puppy_hat.png",src)

cv2.waitKey()
cv2.destroyAllWindows()







(150, 300)
(150, 300, 3)
(150, 300)
(150, 300, 3)


In [44]:
alpha_hat

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [45]:
mask_hat

array([[[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 237, 237],
        [237, 237, 237],
        [237, 237, 237]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 237, 237],
        [237, 237, 237],
        [237, 237, 237]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 237, 237],
        [237, 237, 237],
        [237, 237, 237]],

       ...,

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 237, 237],
        [237, 237, 237],
        [237, 237, 237]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 237, 237],
        [237, 237, 237],
        [237, 237, 237]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 237, 237],
        [237, 237, 237],
        [237, 237, 237]]

In [82]:
mask_hat[ mask_hat>=237] = 0
mask_hat[ mask_hat != 0] = 255
print(mask_hat)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [83]:
cv2.imshow("mask_hat",mask_hat)
cv2.waitKey()
cv2.destroyAllWindows()

In [92]:
img = np.ones((600,1200,3),np.uint8)*255

cv2.line(img,(100,30), (400,30), (0,0,255),5,cv2.LINE_4)
cv2.line(img,(400,30), (100,100), (0,0,255),5,cv2.LINE_4)
cv2.arrowedLine(img,(450,30),(450,300),(0,0,255),5,cv2.LINE_4)
cv2.rectangle(img,(100,400),(450,500),(0,0,255),5,cv2.LINE_4)
cv2.rectangle(img,(120,420),(430,480),(0,255,0),-1,cv2.LINE_4)
cv2.circle(img,(800,200),100,(0,0,255),-1,cv2.LINE_AA)#SMOOSING 해줌
#cv2.ellips(img,center,axes,angle,startAngle,color)
cv2.ellipse(img,(800,200),(50,100),20,0,270,(255,0,255),5,cv2.LINE_4)
cv2.putText(img,"Hello opencv!",(900,400),cv2.FONT_ITALIC,0.8,(123,222,44),2,cv2.LINE_AA)


cv2.imshow("img",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [116]:
img = np.ones((600,1200,3),np.uint8)*255
cv2.circle(img,(100,100),100,(0,0,0),3,cv2.LINE_AA)
cv2.line(img,(230,10), (230,200), (0,0,0),5,cv2.LINE_4)
cv2.line(img,(180,200), (180,300), (0,0,0),5,cv2.LINE_4)
cv2.line(img,(180,300), (250,300), (0,0,0),5,cv2.LINE_4)
cv2.line(img,(300,100), (400,10), (0,0,0),5,cv2.LINE_4)
cv2.line(img,(400,10),(500,100), (0,0,0),5,cv2.LINE_4)
cv2.line(img,(550,10), (550,200), (0,0,0),5,cv2.LINE_4)
cv2.line(img,(550,50), (600,50), (0,0,0),5,cv2.LINE_4)
cv2.rectangle(img,(400,200,150,100),(0,0,0),5,cv2.LINE_4)

cv2.imwrite("./fig/insam.png",img)

cv2.imshow("img",img)
cv2.waitKey()
cv2.destroyAllWindows()