In [19]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical
from numpy import array

In [20]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text = "해보지 않으면 해낼 수 없다"
result = text_to_word_sequence(text)
print(result)

['해보지', '않으면', '해낼', '수', '없다']


In [21]:
docs = ["먼저 텍스트의 각 단어를 나누어 토큰화합니다.", "텍스트의 단어로 토큰화해야 딥러닝에서 인식 됩니다.","토큰화한 결과는 딥러닝에서 사용할 수 있습니다."]
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_counts)

OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식', 1), ('됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [22]:
token.document_count

3

In [23]:
token.word_docs

defaultdict(int,
            {'토큰화합니다': 1,
             '텍스트의': 2,
             '단어를': 1,
             '나누어': 1,
             '각': 1,
             '먼저': 1,
             '인식': 1,
             '딥러닝에서': 2,
             '토큰화해야': 1,
             '단어로': 1,
             '됩니다': 1,
             '수': 1,
             '있습니다': 1,
             '결과는': 1,
             '토큰화한': 1,
             '사용할': 1})

In [24]:
token.word_index

{'텍스트의': 1,
 '딥러닝에서': 2,
 '먼저': 3,
 '각': 4,
 '단어를': 5,
 '나누어': 6,
 '토큰화합니다': 7,
 '단어로': 8,
 '토큰화해야': 9,
 '인식': 10,
 '됩니다': 11,
 '토큰화한': 12,
 '결과는': 13,
 '사용할': 14,
 '수': 15,
 '있습니다': 16}

In [25]:
text = "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [26]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [27]:
word_size = len(token.word_index)+1
x = to_categorical(x,num_classes = word_size)
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [28]:
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화에요","추천하고 싶어요", "한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미 없어요"]
classes = array([1,1,1,1,1,0,0,0,0,0])

token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_docs)

defaultdict(<class 'int'>, {'재밌네요': 1, '너무': 1, '최고예요': 1, '잘': 1, '영화에요': 1, '만든': 1, '참': 1, '추천하고': 1, '싶어요': 1, '더': 1, '한번': 1, '보고싶네요': 1, '글쎄요': 1, '별로예요': 1, '생각보다': 1, '지루하네요': 1, '어색해요': 1, '연기가': 1, '재미': 1, '없어요': 1})


In [29]:
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9], [10, 11, 12], [13], [14], [15, 16], [17, 18], [19, 20]]


In [30]:
word_size = len(token.word_index)+1

In [31]:
padded_x = pad_sequences(x,4)
padded_x

array([[ 0,  0,  1,  2],
       [ 0,  0,  0,  3],
       [ 4,  5,  6,  7],
       [ 0,  0,  8,  9],
       [ 0, 10, 11, 12],
       [ 0,  0,  0, 13],
       [ 0,  0,  0, 14],
       [ 0,  0, 15, 16],
       [ 0,  0, 17, 18],
       [ 0,  0, 19, 20]], dtype=int32)

In [32]:
word_size

21

In [37]:
model = Sequential()
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 4, 8)              168       
                                                                 
 flatten_2 (Flatten)         (None, 32)                0         
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


embedding 21개 단어가 있는데 한 문장당 4개 단어로 구성되 있어 이걸 8차월으로 줄여줘

In [38]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])
model.fit(padded_x,classes,epochs=20)
print(model.evaluate(padded_x,classes))

Epoch 1/20
1/1 [==============================] - 1s 718ms/step - loss: 0.6928 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6910 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6893 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6875 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6858 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 15ms/step - loss: 0.6840 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 20ms/step - loss: 0.6823 - accuracy: 0.5000
Epoch 8/20
1/1 [==============================] - 0s 15ms/step - loss: 0.6805 - accuracy: 0.6000
Epoch 9/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6788 - accuracy: 0.6000
Epoch 10/20
1/1 [==============================] - 0s 14ms/step - loss: 0.6770 - accuracy: 0.6000
Epoch 11/20
1/1 [=============